### ISSUE TITLE
Artsdata minting 'Axion 50 Plus' - Datadog logs

### ISSUE THREAD

**Issue by troughc** [culturecreates/footlight-aggregator#139] opened 2024-11-06 21:56 UTC
@saumier I just minted a. new place - Axion 50 Plus:
https://kg.artsdata.ca/entity.html?uri=http%3A%2F%2Fkg.artsdata.ca%2Fresource%2FK5-1023
I saw that a place already existed; however it is a ROOM inside the building - Axion 50 Plus local 118:
https://kg.artsdata.ca/entity.html?uri=http%3A%2F%2Fkg.artsdata.ca%2Fresource%2FK5-350

Therefore I decided to create the new entity above for the building (K5-1023).

I then saw that k5-350 (the room) appears twice in the cms with 2 different names when you search. In a place search dropdown, under the Artsdata section you see:
- Axion 50 Plus local 118
- Axion 50 Plus
The both link to k5-350. Can we fix that on the artsdata side?

**Comment by troughc** [comment] 2024-11-15 17:39
@saumier this wasn't in the Footlight project board so I moved it as I thought that was what you intended to do? If not, please feel free to move it back to the Artsdata project board...
cc @sahalali

**Comment by troughc** [comment] 2024-11-15 17:40
> Should we add the script to log messages to datadog?

Yes please.

**Comment by saumier** [comment] 2024-11-18 13:00
@sahalali I'm assigning back to you so you can add the log messages to datadog.

**Comment by saumier** [comment] 2024-12-09 22:39
@sahalali Not sure where to look for this in the datadog logs. Can you please provide a link?  Thx.

**Comment by sahalali** [comment] 2024-12-11 06:12
The sync entities logs are modified to match with the aggregator logs.
Please find the logs here: https://app.datadoghq.com/logs?query=host%3Aproduction-server-7%20service%3Afootlight-aggregator&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&context_event=AZO0VunJAACpiWqrWO_aVAAA&event=&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=time%2Cdesc&to_event=AwAAAZO0VunJqU4-6gAAABhBWk8wVnVuSkFBQ3BpV3FyV09fYVZBQUEAAAAkMDE5M2I0NTYtZWI3Mi00NmQzLTk4ZDYtMzBlNTQyMTBkNjkwAAAAAA&viz=&from_ts=1733897115113&to_ts=1733897415114&live=false

**Comment by saumier** [comment] 2024-12-12 03:48
@sahalali I looked into the logs and checked a place mentioned in the log.  It seems to have multiple sameAs to the same  http://kg.artsdata.ca/resource/K5-971.

Is this a bug?

https://api.footlight.io/places/6704f67779a36600640acf45

**Comment by sahalali** [comment] 2024-12-13 09:42
@saumier I could not find the sameAs getting duplicated in the given place. Did you remove it from your end?

**Comment by saumier** [comment] 2024-12-13 13:01
@SuhailAliyar No. I did not remove it at my end. I looked at the example above and did not see it either.  Lets ask the team if anyone has an idea what happened. The duplicated Artsdata IDs were in all the events I checked. But I only checked about 3 or 4.

**Comment by troughc** [comment] 2024-12-17 19:41
@sahalali @saumier who should this issue be assigned to in order to follow up on your questions?

**Comment by sahalali** [comment] 2024-12-18 11:31
@saumierI've checked with the team, and we did not do anything on this. What is the next step regarding this issue? Should we consider this closed since we could not reproduce it, or should we continue a detailed investigation?

**Comment by saumier** [comment] 2024-12-18 23:32
@sahalali @troughc I am closing this issue.   The Place Axion 50 Plus in the CMS is now linked to Artsdata.

**Closed by saumier** 2024-12-18 23:32 UTC
Labels: bug
